import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center h-screen gap-8">
          <nav className="bg-white shrink-0 border-b border-slate-300 w-full flex justify-center items-center h-20 sticky top-0">
            <h1 className="w-full max-w-4xl px-5 font-bold text-2xl">
              <a href="/">Blog</a>
            </h1>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
